### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 18

### ISSUE THREAD

**Issue by MartinOrtel** [MartinOrtel/FoerdermittelVerwaltung#1]
**[in app/config/security.yml, line 18](https://github.com/MartinOrtel/FoerdermittelVerwaltung/blob/4acc01d1b21f9c3695ad70c7c18b1e81ad29e139/app/config/security.yml#L18)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/ab54db5d-520f-4bc2-af44-0c3860883f4e/analyses/1)_
